AS=yasm
SRC=$(wildcard src/$(ARCH)/*.s)
OBJ=$(SRC:.s=.o)
TESTDIR=test/
TARGET=lib/libstring_asm.a

all: $(TARGET) test

$(TARGET): $(OBJ)
	ar rv $@ $^

%.o: %.s
	$(AS) $(ASFLAGS) -o $@ $^

.PHONY: clean mrproper rebuild test

clean:
	@rm -f $(OBJ)
	@rm -f $(TESTDIR)*.bin

mrproper: clean
	@rm -f $(TARGET)

rebuild: mrproper all

test: $(TARGET)
	@cd $(TESTDIR) && ./test $(TESTFLAGS)
